name: Build Tomcat

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out tomcat-users.xml
              uses: actions/checkout@v2

            - name: List project files an dava version
              run: |
                ls -ltr
                java -version

            - name: Check out Apache Tomcat
              uses: actions/checkout@v2
              with:
                repository: apache/tomcat
                ref: master
                path: ./tomcat

            - name: List project files an dava version
              run: |
                ls -ltr
                java -version